### ISSUE TITLE
re-run beforeEnter guards

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [lulupointu/vrouter#212] opened 2023-02-27 19:04 UTC
Add method ```context.vRouter.refresh();``` to refresh page for re-running ```beforeEnter``` guards after auth state changes
like in ```go_router``` https://pub.dev/documentation/go_router/latest/go_router/GoRouter/refresh.html

**Comment by lulupointu** [comment] 2023-03-07 22:33
This means keeping the same Url but wiping all the state of the application?

**Comment by lulupointu** [comment] 2023-03-07 22:54
If so you could build a widget to do this for you.

<details>
<summary>
Here is an example of how
</summary>

```dart

class RefresherWidget extends StatefulWidget {
  const RefresherWidget({
    Key? key,
    required this.builder,
  }) : super(key: key);

  final Widget Function(
    GlobalKey<VRouterState> routerKey,
    String? initialUrlOverride,
  ) builder;

  static void refresh(BuildContext context) {
    final _RefresherInheritedWidget? result =
        context.dependOnInheritedWidgetOfExactType<_RefresherInheritedWidget>();
    assert(result != null, 'No RefreshWidget found in context');
    result!._refresh();
  }

  @override
  State<RefresherWidget> createState() => _RefresherWidgetState();
}

class _RefresherWidgetState extends State<RefresherWidget> {
  var routerKey = GlobalKey<VRouterState>();
  String? initialUrlOverride;

  void refresh() {
    setState(() {
      final routerState = routerKey.currentState;
      if (routerState != null) {
        initialUrlOverride = routerState.url;
      }
      routerKey = GlobalKey<VRouterState>();
    });
  }

  @override
  Widget build(BuildContext context) {
    final localInitialUrlOverride = initialUrlOverride;
    initialUrlOverride = null;

    return _RefresherInheritedWidget(
      refresh: refresh,
      child: widget.builder(routerKey, localInitialUrlOverride),
    );
  }
}

class _RefresherInheritedWidget extends InheritedWidget {
  const _RefresherInheritedWidget({
    Key? key,
    required VoidCallback refresh,
    required Widget child,
  })  : _refresh = refresh,
        super(key: key, child: child);

  final VoidCallback _refresh;

  @override
  bool updateShouldNotify(_RefresherInheritedWidget old) {
    return false;
  }
}
```

</details>

You would have to wrapped `VRouter` in it:
```dart
RefresherWidget(
  builder: (routerKey, initialUrlOverride) {
    return VRouter(
      key: routerKey,
      initialUrl: initialUrlOverride ?? '/',
      routes: [
        ...
      ],
    );
  },
)
```

And could then use it like this:
```dart
RefresherWidget.refresh(context)
```

**Comment by AlaaEldeenYsr** [comment] 2023-03-08 19:38
I dont't want to reset the app state
I just want to re-run the current active routes middlewares (guards) to decide whether to stay as they are or to handle some redirects
@lulupointu

**Comment by lulupointu** [comment] 2023-03-08 22:09
I see why it's not the same. I'm wondering why you can't use `beforeUpdate` in this case instead. Could you maybe share your use case with a simple code to reproduce it so that I can see more clearly?

**Comment by lulupointu** [comment] 2023-04-28 17:44
Closing since this would be a large implementation task to support this out of the box. I would rather see a concrete small example where you can't achieve this without a change in `vRouter` to then evaluate the impact of the feature. 
If you have such an example, feel free to reopen the issue to restart the conversation!

**Closed as completed by lulupointu** 2023-04-28 17:44 UTC
