### ISSUE TITLE
Change routing structure on runtime without loosing widget state

### ISSUE THREAD

**Issue by saibotma** [lulupointu/vrouter#195] opened 2022-06-20 05:57 UTC
As stated in #89  it is possible to change routing structure dynamically by changing the navigator key. Unfortunately, then all widgets lose their state. Obviously we can store some state in external state management, however it is very tedious to persist text selection or scrolling state in there.

I created a small example showcasing what I want to achieve. The example is a split view, that shows a list on the left and details on the right. When there is enough space, then both list and details should be shown next to each other. Otherwise, only one of them, depending on whether the details route is active or not, should be shown. The details route should be wrapped in a nested navigator to have page transitions only on that part of the screen, in case the details tree expands further in a more sophisticated app.

https://user-images.githubusercontent.com/26022902/174534443-f9186696-d207-4bd9-9d95-2b96858f21c5.mov

<details>
<summary>Example code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  var _navigatorKey = GlobalKey<NavigatorState>();
  bool? _isSmall;

  @override
  Widget build(BuildContext context) {
    const listRouteKey = ValueKey("listRoute");
    const listKey = ValueKey("list");
    const detailRouteKey = ValueKey("detailRoute");
    const detailKey = ValueKey("detail");

    return LayoutBuilder(
      builder: (context, constraints) {
        final isSmall = constraints.maxWidth <= 500;
        if (isSmall != _isSmall) {
          _navigatorKey = GlobalKey<NavigatorState>();
          _isSmall = isSmall;
        }

        return VRouter(
          navigatorKey: _navigatorKey,
          initialUrl: "/list",
          routes: [
            if (_isSmall == true) ...[
              VWidget(
                key: listRouteKey,
                path: "/list",
                widget: const List(
                  key: listKey,
                  child: null,
                ),
                stackedRoutes: [
                  VWidget(
                    key: detailRouteKey,
                    path: "detail",
                    widget: const Detail(key: detailKey),
                  )
                ],
              ),
            ] else ...[
              VNester(
                key: listRouteKey,
                path: "/list",
                widgetBuilder: (child) {
                  return List(
                    key: listKey,
                    child: child,
                  );
                },
                nestedRoutes: [
                  VWidget(
                    key: detailRouteKey,
                    path: "detail",
                    widget: const Detail(key: detailKey),
                  ),
                  VWidget(
                    path: null,
                    widget: Container(
                      color: Colors.white,
                      alignment: Alignment.center,
                      child: const Text("No content"),
                    ),
                  )
                ],
              ),
            ]
          ],
        );
      },
    );
  }
}

class List extends StatelessWidget {
  final Widget? child;

  const List({required this.child, Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SplitView(
      left: Container(
          color: Colors.orange,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              ElevatedButton(
                onPressed: () => context.vRouter.to("/list/detail"),
                child: const Text("to detail"),
              ),
              const SizedBox(height: 8),
              ElevatedButton(
                onPressed: () => context.vRouter.to("/list"),
                child: const Text("to list"),
              ),
              const SizedBox(height: 16),
              const Counter(),
            ],
          )),
      right: child,
    );
  }
}

class Detail extends StatelessWidget {
  const Detail({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(color: Colors.green, child: const Counter());
  }
}

class Counter extends StatefulWidget {
  const Counter({Key? key}) : super(key: key);

  @override
  State<Counter> createState() => _CounterState();
}

class _CounterState extends State<Counter> {
  int _count = 0;

  @override
  Widget build(BuildContext context) {
    return Center(
      child: ElevatedButton(
        onPressed: () => setState(() => _count++),
        child: Text(_count.toString()),
      ),
    );
  }
}

class SplitView extends StatelessWidget {
  final Widget left;
  final Widget? right;

  const SplitView({required this.left, this.right, Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    if (right == null) {
      return left;
    }

    return Row(
      children: [
        SizedBox(width: 400, child: left),
        Container(width: 1, color: Colors.black),
        Expanded(child: ClipRect(child: right!)),
      ],
    );
  }
}
```

</details>

**Comment by lulupointu** [comment] 2023-04-28 22:02
There is actually a way to achieve what you want.

What you really want is for Flutter to understand that even if the widget tree changes, the `Detail` and `List` widget are actually the same. To do this Flutter gives us the `GlobalKey` object.

There is 1 important thing to keep in mind though, two widgets with the same `GlobalKey` can not be used in the tree at the same time. This seems easy enough but we have a bit of a edge case when we update from _narrow layout_ to _wide layout_. The issue is that the `Detail` widget is `popped` from the stack (with an animation out) and placed in the `List` widget. Therefore, while the out transition runs, the `Detail` widget is at 2 places in the widget tree. I could not find a fix for this. One fix could be to use a custom transition which does nothing if the layout changes but this is not very satisfying. In any case, I do believe this is the right direction.

One last thing: To keep the state of a subtree, you have to:
  1. Use a global key
  2. Keep the same subtree structure
The issue was that the `left` widget of the `SplitView` was placed in a different parent depending on whether right is null or not (if `right == null`: `SplitView>left` if `right != null`: `SplitView>Row>SizedBox>left`). Therefore, when going from right is null to not null, the state of `left` was lost because Flutter though they are 2 different widgets. To solve this you have 2 solutions:
  1. Use a globalKey on `left`
  2. Use the same structure
I would often recommend trying the second because the constraint on the fast that you can't have twice the same globalKey in the tree always make `GlobalKey`s harder to work with.


<details>
<summary>

Anyway, based on those 3 fixes, here is a way to achieve want you want: (though the reverse transition is brolen as explained in my second point)

</summary>

```dart
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  var _navigatorKey = GlobalKey<NavigatorState>();
  final _listKey = GlobalKey();
  final _detailKey = GlobalKey();
  bool? _wasSmall;
  final listRouteKey = const ValueKey("listRoute");
  final detailRouteKey = const ValueKey("detailRoute");

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        final isSmall = constraints.maxWidth <= 500;
        final layoutUpdate = _wasSmall != null && isSmall != _wasSmall;
        if (layoutUpdate) {
          _navigatorKey = GlobalKey<NavigatorState>();
        }

        _wasSmall = isSmall;

        return VRouter(
          navigatorKey: _navigatorKey,
          initialUrl: "/list",
          routes: [
            if (isSmall == true) ...[
              VWidget(
                key: listRouteKey,
                path: "/list",
                widget: List(
                  key: _listKey,
                  child: null,
                ),
                stackedRoutes: [
                  VWidget(
                    key: detailRouteKey,
                    path: "detail",
                    // Remove the reverse transition otherwise [Detail] is present
                    // twice in the tree which is an issue because it has a
                    // [GlobalKey]
                    reverseTransitionDuration: const Duration(milliseconds: 0),
                    widget: Detail(key: _detailKey),
                  ),
                ],
              ),
            ] else ...[
              VNester(
                key: listRouteKey,
                path: "/list",
                widgetBuilder: (child) {
                  return List(
                    key: _listKey,
                    child: child,
                  );
                },
                nestedRoutes: [
                  VWidget(
                    key: detailRouteKey,
                    path: "detail",
                    widget: Detail(
                      key: _detailKey,
                    ),
                  ),
                  VWidget(
                    path: null,
                    widget: Container(
                      color: Colors.white,
                      alignment: Alignment.center,
                      child: const Text("No content"),
                    ),
                  )
                ],
              ),
            ]
          ],
        );
      },
    );
  }
}

class List extends StatelessWidget {
  final Widget? child;

  const List({required this.child, Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SplitView(
      left: Container(
          color: Colors.orange,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              ElevatedButton(
                onPressed: () => context.vRouter.to("/list/detail"),
                child: const Text("to detail"),
              ),
              const SizedBox(height: 8),
              ElevatedButton(
                onPressed: () => context.vRouter.to("/list"),
                child: const Text("to list"),
              ),
              const SizedBox(height: 16),
              const Counter(),
            ],
          )),
      right: child,
    );
  }
}

class Detail extends StatelessWidget {
  const Detail({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(color: Colors.green, child: const Counter());
  }
}

class Counter extends StatefulWidget {
  const Counter({Key? key}) : super(key: key);

  @override
  State<Counter> createState() => _CounterState();
}

class _CounterState extends State<Counter> {
  int _count = 0;

  @override
  Widget build(BuildContext context) {
    return Center(
      child: ElevatedButton(
        onPressed: () => setState(() => _count++),
        child: Text(_count.toString()),
      ),
    );
  }
}

class SplitView extends StatelessWidget {
  final Widget left;
  final Widget? right;

  const SplitView({required this.left, this.right, Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final right = this.right;

    return Row(
      children: [
        SizedBox(width: 400, child: left),
        if (right != null) ...[
          Container(width: 1, color: Colors.black),
          Expanded(child: ClipRect(child: right)),
        ],
      ],
    );
  }
}

```

</details>

I think the should be enough for you to start thinking of the right solution for you. I'll close this for now, feel free to reopen if you need more help.

**Closed as completed by lulupointu** 2023-04-28 22:02 UTC
