### ISSUE TITLE
Support for observers

### ISSUE THREAD

**Issue by CosmicPangolin** [lulupointu/vrouter#49] opened 2021-04-18 05:46 UTC
It'd be nice to have VRouter or VMaterialApp support observers.  It looks like this functionality is basically there for VMaterialApp, the class just needs a passthrough variable to give VRouterDelegate.

**Comment by lulupointu** [comment] 2021-04-18 08:54
> It looks like this functionality is basically there for VMaterialApp
I don't understand what you mean. `VMaterialApp` does not have an `observable` property.

Could you specify your use case? Do you want to observe `VRouter` ? A navigator ? Could you provide a small code snippet of what you are trying to achieve and how you see it maybe ?

**Comment by lulupointu** [comment] 2021-04-18 09:29
I think I understand what you mean. The issue is that VRouter creates nested navigator. 

Describing your use case you really help me understand your needs then.

**Comment by CosmicPangolin** [comment] 2021-04-18 21:19
Sure...the firebase analytics package has a FirebaseAnalyticsObserver that reports on route changes.

https://pub.dev/documentation/firebase_analytics/latest/observer/FirebaseAnalyticsObserver-class.html

I need to use this to observe navigation throughout the app, including in nested navigators :)

**Comment by lulupointu** [comment] 2021-04-18 22:05
I see, I would need to make more tests but I should be able to make this work.

You will have to wait same time though since it's not as simple as passing the navigator observer down, maybe a week, max 2 I would say.

Thanks for bringing this feature of Firebase btw, very interesting!

**Comment by lulupointu** [comment] 2021-04-27 16:15
`navigatorObservers` can now be given to `VRouter`.

The name that will be observed in the \FirebaseAnalyticsObserver` will be either the name of the `VWidget` (if you give it one) or the path of the `VWidget`, with the pathParameters replaced.

I keep this open because I would love to have a feedback on this since I did not extensively test it. Feel free to close it if you don't want/can't leave a feedback :)

**Comment by lulupointu** [comment] 2021-05-04 09:00
Did you have the chance to have a look ?

**Comment by evandrmb** [comment] 2021-05-28 20:03
Hi, I didn't try with FirebaseObserver, but my project uses `BotToastNavigatorObserver` and my own `RouteObserver` to implement `RouteAware` (even tho in some cases we can achieve the same result with VGuard) and it's working good!

**Comment by lulupointu** [comment] 2021-05-28 20:11
Oh great, thanks for the input!

**Comment by lulupointu** [comment] 2021-06-05 09:12
Since it's working for @evandrmb I'll close this issue. @CosmicPangolin feel free to reopen it or open a new one if you have an issue with this.

**Closed by lulupointu** 2021-06-05 09:12 UTC
Labels: waiting for response

**Comment by evandrmb** [comment] 2021-06-05 15:35
Also, sorry for the late feedback:
![image](https://user-images.githubusercontent.com/47798920/120896970-51cfc980-c5fa-11eb-835b-4139aa4c36bb.png)
I've simulated some bugs in my software and Sentry's observer worked just fine.👍

**Comment by lulupointu** [comment] 2021-06-05 16:13
No worries! Thanks for taking the time to respond anyway. I'm glad it works then 😉
