### ISSUE TITLE
After pop VWidgetGuard still in the _vWidgetGuardMessagesRoot

### ISSUE THREAD

**Issue by sirjasiu** [lulupointu/vrouter#52] opened 2021-04-25 16:23 UTC
I have quite a simple login on the stacked page, do not pop (system pop) until some requirements are met. And it works. Unfortunately, even after popping the page, the same login is called even on the parent pages.
Of course, it ends with the exception: 

> Looking up a deactivated widget's ancestor is unsafe.
> At this point the state of the widget's element tree is no longer stable

System pop is not longer working ;)

**Comment by lulupointu** [comment] 2021-04-25 16:27
Could you provide a small reproducible example ? :)

**Comment by sirjasiu** [comment] 2021-04-25 16:32
I believe the problem is (but just after quick reading a code) that in the push you are trying to decide which guard are already deactivated and which reused, in the systemPop (and pop, btw) you are using all of them). I'll try to create something quick.

**Comment by lulupointu** [comment] 2021-04-25 16:34
Oh I think I see your issue.

Yes currently every onPop of the current route is called even if they don't pop. That's not a bug but definitely something I want to change.

**Comment by sirjasiu** [comment] 2021-04-25 16:42
```
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

void main() {
  runApp(
    VRouter(
      routes: [
        VWidget(path: '/', widget: HomeScreen(),
        stackedRoutes: [
          VWidget(path: 'settings', widget: SettingsScreen(),
              stackedRoutes: [
                VWidget(path: 'no_pop', widget: NoSystemPopWidget())
              ]
          ),
        ]),
      ],
    ),
  );
}

abstract class BaseWidget extends StatelessWidget {
  String get title;

  String get buttonText;

  String get pushTo;

  @override
  Widget build(BuildContext context) {
    return Material(
      child: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(title),
            SizedBox(height: 50),
            ElevatedButton(
              onPressed: () => context.vRouter.push(pushTo),
              child: Text(buttonText),
            ),
          ],
        ),
      ),
    );
  }
}

class HomeScreen extends BaseWidget {
  @override
  String get title => 'Home';

  @override
  String get buttonText => 'Go to Settings';

  @override
  String get pushTo => '/settings';
}

class SettingsScreen extends BaseWidget {
  @override
  String get title => 'Settings';

  @override
  String get buttonText => 'Go to No Pop';

  @override
  String get pushTo => 'no_pop';
}

 class NoSystemPopWidget extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return VWidgetGuard(
      onSystemPop: (vredirector) async {
        vredirector.stopRedirection();
      },
      child: Material(
        child: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Text("Non system pop"),
              SizedBox(height: 50),
              ElevatedButton(
                onPressed: () => context.vRouter.pop(),
                child: Text("Do pop"),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

**Comment by sirjasiu** [comment] 2021-04-25 16:45
NO, this is not what I meant. There are called onPops even of the pages that where already poped. In the example above, systemPop works when you get the first time to the settings page. Then on the NoPop page systemPop is distabled, by design, you can only call pop method and get back to the settings page. But now, event on the settings page, systemPop is not longer available, VWidgetGuard is called even here, despite the NoPop page is already 'poped'.

**Comment by sirjasiu** [comment] 2021-04-25 16:46
By the way, love your package :D

**Comment by lulupointu** [comment] 2021-04-25 16:59
Thanks, I can reproduce this and this is definitely a bug. I'm not sure why this happens but I'll look into it !

**Comment by sirjasiu** [comment] 2021-04-25 17:53
It looks like after the pop the list of _vWidgetGuardMessagesRoot is not modified (I thought it can be somehow marked and reused, but since there might be some references to the current state of the widget, it just needs to be removed from the list).

**Comment by lulupointu** [comment] 2021-04-25 18:45
Yes I agree but I tried removing them just now and it does not work I don't know why.I'll need a bit more time to look into it.in the meantime you can use VPopHandler as a VRouteElement, this works like a charm.

**Comment by sirjasiu** [comment] 2021-04-25 19:11
I'm using guard for some modification in the page (stepper, back button get back to the previous step, and not pop the page itself, at least until the first step) - having this logic outside of the widget might be harder to implement, and I can wait :D at least if you say it can be handled this way 😄 
thanks for help

**Comment by sirjasiu** [comment] 2021-04-25 19:14
btw, there was an exception thrown in my guard, since the state of my widget was no longer available. This exception was somehow caught and handled and not even a message about it was mentioned in logs - I had to debug to find what is wrong. And it took me a while since I was not aware that this going to another page was a reason ;)

**Comment by lulupointu** [comment] 2021-04-25 19:17
I think this should be fixable. Otherwise it means throwing out `VWidgetGuard`which I really don't want!

I don't know why the error did not show either, I'm not handling many errors on my end but I'll look into it too.

**Comment by lulupointu** [comment] 2021-04-25 19:54
Oh ok nevermind this was easy. I just forgot to remove them when needed. 

I'll ship the fix soon

**Comment by lulupointu** [comment] 2021-04-27 16:04
Fixed in `v1.1.1`

**Comment by sirjasiu** [comment] 2021-04-27 16:38
Some problem on flutter 2.0.5
../../../flutter/flutter/.pub-cache/hosted/pub.dartlang.org/vrouter-1.1.1+1/lib/src/vrouter/cupertino_vrouter.dart:457:7: Error: No named parameter with the name 'scrollBehavior'.
      scrollBehavior: widget.scrollBehavior,
      ^^^^^^^^^^^^^^
../../../flutter/flutter/packages/flutter/lib/src/cupertino/app.dart:181:9: Context: Found this candidate, but the arguments don't match.
  const CupertinoApp.router({
        ^^^^^^^^^^^^^^^^^^^

**Comment by lulupointu** [comment] 2021-04-27 16:40
Can you provide a small snippet ?

**Comment by lulupointu** [comment] 2021-04-27 16:48
Oh nvm got it !
Thanks!

I'm spending too much time in master ^^

**Closed by lulupointu** 2021-04-27 16:48 UTC
Labels: has reproducible steps
