### ISSUE TITLE
VNester changing render semantics/layout constraints for children

### ISSUE THREAD

**Issue by CosmicPangolin** [lulupointu/vrouter#55] opened 2021-04-30 00:36 UTC
Consider a VNester wrapping routes in a simple Scaffold widget composed of a Stack with some aligned children.

```
VNester(
    path: '/',
    widgetBuilder: (child) => SimpleScaffold(
      header: TransparentHeader(),
      drawer: NavigationDrawer(),
      child: child,
    ),
    nestedRoutes: [
      VWidget(
        path: 'about',
        widget: AboutCard(),
      ),
    ],
  ),
```

```
class SimpleScaffoldextends StatefulWidget {
  const SimpleScaffold({
    @required this.header,
    @required this.drawer,
    @required this.child,
  });
  final Widget header;
  final Widget drawer;
  final Widget child;
  @override
  _SimplesScaffoldState createState() => _SimpleScaffoldState();
}

class _SimpleScaffoldState extends State<SimpleScaffold> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      endDrawer: widget.drawer,
      body: Stack(
        children: [
          Align(
            alignment: Alignment.topCenter,
            child: widget.header,
          ),
          Align(
            alignment: Alignment.bottomCenter,
            child: widget.child, // AboutCard()
          ),
        ],
      ),
    );
  }
}
```

I've found that a widget tree constructed through a VNester has different layout constraints than the direct construction. Using widgetBuilder thus causes unnatural layout behavior like stretching fixed-height children to fill the screen in certain layouts.  Eg, If I replace widget.child with AboutCard() (a fixed height widget w/ a column child) in SimpleScaffold, I get a fixed-height widget result aligned to bottom center (as expected) vs. the widgetBuilder result that stretches to fill the screen. 

This can also be seen in different render semantics:

**Injected with widgetBuilder**
![image](https://user-images.githubusercontent.com/40650466/116634256-6987a400-a910-11eb-8d75-1e0c0ab8e185.png)

**Passed directly**
![image](https://user-images.githubusercontent.com/40650466/116634301-7f956480-a910-11eb-9602-0dd5c6065def.png)

**Comment by lulupointu** [comment] 2021-04-30 06:15
Thanks for the input, indeed there is an issue here

**Comment by lulupointu** [comment] 2021-04-30 07:21
Actually the issue is already tracked here: https://github.com/flutter/flutter/issues/14803#issue-298978507

*Unfortunately* this does not depend on `VRouter`.

*Fortunately* there is an easy fix: move the constraint down.

Here is the solution for your particular case:

```dart
VNesterBase(
  widgetBuilder: (child) => SimpleScaffold(
    header: Text('Header'),
    child: child,
  ),
  nestedRoutes: [
    VWidget(
      path: '/about',
      widget: Align(
        alignment: Alignment.bottomCenter,
        child: AboutCard(),
      ),
    ),
  ],
)
```

```dart
class _SimpleScaffoldState extends State<SimpleScaffold> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          Align(
            alignment: Alignment.topCenter,
            child: widget.header,
          ),
          widget.child, // AboutCard(),
        ],
      ),
    );
  }
}
```

Feel free to close and follow on the linked issue (as well as giving a thumb up here https://github.com/flutter/flutter/issues/14803#issue-298978507)

**Comment by CosmicPangolin** [comment] 2021-04-30 21:10
@lulupointu 

Your fix almost works...while the layout **_looks_** right, it still changes the semantics such that the child widget captures gestures for the entire page even when it's fixed-height and aligned bottom.

**Comment by lulupointu** [comment] 2021-05-01 11:36
I think you are just wrapping the wrong widget, this works for example:

```dart
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

main() {
  runApp(
    VRouter(
      initialUrl: '/about',
      routes: [
        VNesterBase(
          widgetBuilder: (child) => SimpleScaffold(
            header: Container(color: Colors.red, child: Text('Header')),
            child: child,
          ),
          nestedRoutes: [
            VWidget(
              path: '/about',
              widget: Align(
                alignment: Alignment.bottomCenter,
                child: AboutCard(),
              ),
            ),
          ],
        ),
      ],
    ),
  );
}

class SimpleScaffold extends StatefulWidget {
  final Widget header;
  final Widget child;

  const SimpleScaffold({
    Key? key,
    required this.header,
    required this.child,
  }) : super(key: key);

  @override
  _SimpleScaffoldState createState() => _SimpleScaffoldState();
}

class _SimpleScaffoldState extends State<SimpleScaffold> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GestureDetector(
        onTap: () => print('TAP'),
        child: Container(
          color: Colors.amberAccent,
          child: Stack(
            children: [
              Align(
                alignment: Alignment.topCenter,
                child: widget.header,
              ),
              IgnorePointer(child: widget.child), // AboutCard(),
            ],
          ),
        ),
      ),
    );
  }
}

class AboutCard extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(color: Colors.red, child: Text('ABOUT'));
  }
}
```

The thing is that the `VWidget.widget` is wrapped in a `Navigator`, so putting a `IgnorePointer` is not working because the `IgnorePointer` is bellow the `Navigator`.
Putting the `IgnorePointer` on top `SimpleScaffold.child` means that you DO wrap the `Navigator` in an `IgnorePointer`.

Sorry for this, this is not ideal but at least there are some easy workaround.

**Comment by CosmicPangolin** [comment] 2021-05-02 01:12
No worries, I'm all for workarounds.  Since this Flutter issue has been open since 2018, I'm not holding my breath for a quick fix :)

However, the solution you provide doesn't work for my use case (I don't think...).  I want to be able to hit buttons below the child in the stack (eg, buttons in the header), and wrapping the scaffold child in a translucent GestureDetector doesn't help :|

Thanks for the quick replies!

**Comment by lulupointu** [comment] 2021-05-02 09:58
I'm sorry if this does not work I think I don't understand what you want.

Could you provide a small snippet which does not work but where the button and the obstructing widget are placed how they should so that I can try to make it work?

**Comment by lulupointu** [comment] 2021-05-04 08:57
Any luck?

**Comment by CosmicPangolin** [comment] 2021-05-04 17:50
Haven't forgotten, just stuck on other work...will post it for ya in a day or two :)

**Comment by CosmicPangolin** [comment] 2021-05-08 22:34
@lulupointu  Here ya go!

```
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

class RouterTest extends StatefulWidget {
  @override
  _RouterTestState createState() => _RouterTestState();
}

class _RouterTestState extends State<RouterTest> {
  @override
  Widget build(BuildContext context) {
    return VRouter(
      mode: VRouterModes.history,
      debugShowCheckedModeBanner: false,
      title: 'RouterTest',
      routes: [
        VWidget(
          path: '/',
          widget: _RouterScaffold(
            header: _TransparentHeader(),
            child: Container(),
          ),
        ),
        VNester(
          path: '/',
          widgetBuilder: (child) => _RouterScaffold(
            header: _TransparentHeader(),
            // TODO: Have to put Align here because of flutter layout
            // TODO: issues - https://github.com/flutter/flutter/issues/14803#issue-298978507
            child: child,
          ),
          nestedRoutes: [
            VWidget(
              path: 'about',
              widget: Align(
                alignment: Alignment.bottomCenter,
                child: _AboutCard(),
              ),
            ),
          ],
        ),
        VRouteRedirector(
          // This matches any path
          path: ':_(.+)',
          redirectTo: '/',
        ),
      ],
    );
  }
}

class _RouterScaffold extends StatefulWidget {
  const _RouterScaffold({
    @required this.header,
    @required this.child,
  });
  final Widget header;
  final Widget child;
  @override
  __RouterScaffoldState createState() => __RouterScaffoldState();
}

class __RouterScaffoldState extends State<_RouterScaffold> {
  @override
  Widget build(BuildContext context) => Scaffold(
        body: Stack(
          children: [
            Container(
              width: MediaQuery.of(context).size.width,
              height: MediaQuery.of(context).size.height,
              child: Container(color: Colors.grey.shade50,)
            ),
            Align(
              alignment: Alignment.topCenter,
              child: widget.header,
            ),
            widget.child,
          ],
        ),
      );
}

class _TransparentHeader extends StatefulWidget {
  @override
  _TransparentHeaderState createState() => _TransparentHeaderState();
}

class _TransparentHeaderState extends State<_TransparentHeader> {
  @override
  Widget build(BuildContext context) {
    return Stack(
      fit: StackFit.expand,
      children: [
        Align(
          alignment: Alignment.topCenter,
          child: Container(
            width: MediaQuery.of(context).size.width * 1 / 2,
            // Same as IconButton height
            height: 40,
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                TextButton(
                  onPressed: () {
                    VRouter.of(context).push('/about');
                  },
                  child: Text(
                    'Route To About Card',
                    textScaleFactor: 1.25,
                  ),
                ),
                TextButton(
                  onPressed: () {},
                  child: Text(
                    'Try to press meeeee',
                    textScaleFactor: 1.25,
                  ),
                ),

              ],
            ),
          ),
        ),
      ],
    );
  }
}

class _AboutCard extends StatefulWidget {
  @override
  _AboutCardState createState() => _AboutCardState();
}

class _AboutCardState extends State<_AboutCard>
    with SingleTickerProviderStateMixin {
  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: DefaultTabController(
        length: 3,
        child: Card(
          color: Colors.white.withOpacity(0.5),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              TabBar(
                tabs: [
                  Tab(
                    text: "Our Story",
                  ),
                  Tab(
                    text: "Our Process",
                  ),
                ],
              ),
              Container(
                // TODO: Move to better place when flutter fixes the nav shit
                height: MediaQuery.of(context).size.height * 0.75,
                child: TabBarView(
                  children: [
                    Container(color: Colors.purple,),
                    Container(color: Colors.amber,),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

**Comment by lulupointu** [comment] 2021-05-09 07:50
I tried to make it work without changing your code but unfortunately I could not do it.

However, looking at your code in detail I think the issue is more how you build your layout. Maybe are you trying to do something that I could not see and which will not work with what I did but basically you seem to be using way too many stacks.

<details>
<summary>
Here is my solution
</summary>

```dart
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

main() {
  runApp(RouterTest());
}

class RouterTest extends StatefulWidget {
  @override
  _RouterTestState createState() => _RouterTestState();
}

class _RouterTestState extends State<RouterTest> {
  @override
  Widget build(BuildContext context) {
    return VRouter(
      mode: VRouterModes.history,
      debugShowCheckedModeBanner: false,
      title: 'RouterTest',
      routes: [
        VWidget(
          path: '/',
          widget: _RouterScaffold(
            header: _TransparentHeader(),
            child: Container(),
          ),
        ),
        VNester(
          path: '/',
          widgetBuilder: (child) => _RouterScaffold(
            header: _TransparentHeader(),
            // TODO: Have to put Align here because of flutter layout
            // TODO: issues - https://github.com/flutter/flutter/issues/14803#issue-298978507
            child: child,
          ),
          nestedRoutes: [
            VWidget(
              path: 'about',
              widget: _AboutCard(),
            ),
          ],
        ),
        VRouteRedirector(
          // This matches any path
          path: ':_(.+)',
          redirectTo: '/',
        ),
      ],
    );
  }
}

class _RouterScaffold extends StatefulWidget {
  const _RouterScaffold({
    required this.header,
    required this.child,
  });

  final Widget header;
  final Widget child;

  @override
  __RouterScaffoldState createState() => __RouterScaffoldState();
}

class __RouterScaffoldState extends State<_RouterScaffold> {
  @override
  Widget build(BuildContext context) => Scaffold(
        body: Container(
          color: Colors.grey.shade50,
          child: Column(
            children: [
              widget.header,
              Expanded(child: widget.child),
            ],
          ),
        ),
      );
}

class _TransparentHeader extends StatefulWidget {
  @override
  _TransparentHeaderState createState() => _TransparentHeaderState();
}

class _TransparentHeaderState extends State<_TransparentHeader> {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: MediaQuery.of(context).size.width * 1 / 2,
      // Same as IconButton height
      height: 40,
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          TextButton(
            onPressed: () {
              VRouter.of(context).push('/about');
            },
            child: Text(
              'Route To About Card',
              textScaleFactor: 1.25,
            ),
          ),
          TextButton(
            onPressed: () {
              print('ok');
            },
            child: Text(
              'Try to press meeeee',
              textScaleFactor: 1.25,
            ),
          ),
        ],
      ),
    );
  }
}

class _AboutCard extends StatefulWidget {
  @override
  _AboutCardState createState() => _AboutCardState();
}

class _AboutCardState extends State<_AboutCard> with SingleTickerProviderStateMixin {
  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: DefaultTabController(
        length: 2,
        child: Card(
          color: Colors.white.withOpacity(0.5),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              TabBar(
                tabs: [
                  Tab(
                    text: "Our Story",
                  ),
                  Tab(
                    text: "Our Process",
                  ),
                ],
              ),
              Container(
                // TODO: Move to better place when flutter fixes the nav shit
                height: MediaQuery.of(context).size.height * 0.75,
                child: TabBarView(
                  children: [
                    Container(
                      color: Colors.purple,
                    ),
                    Container(
                      color: Colors.amber,
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

BTW you should not use statefull widget unless you need to, in you case you don't need any (maybe that's because you removed some part idk but I thought I would tell you).

Also I saw that you have a `TabBarView`, if you need inspiration of how to link it to `VRouter` you can use this example: https://github.com/flutter/uxr/blob/master/nav2-usability/scenario_code/lib/nested-routing/nested_routing_vrouter.dart

Hope this helps!

**Comment by CosmicPangolin** [comment] 2021-05-12 20:47
Unfortunately your solution reduces the complexity of the layout by substituting Cols and Rows for Stacks, which just reaffirms that the underlying flutter bug exists and drastically limits the routing functionality available w/ nested routes 😛 

Though my layout appears complex in the reduced example, in practice the stacks are required in my widget tree to express several things that I need: a stack of aligned/positioned items in a complex header and a stack of application components aligned/positioned over a full-screen background image.  Stack widgets serve a distinct purpose and can't just be substituted away for widgets that don't offer positioning and overlay semantics.

Tbh I feel like this underlying framework bug is a _huge roadblock_ for properly building declarative nested navigation.  Because of the layout semantics translation that occurs, the end user is prohibited from using an entire subset of the flutter framework which can otherwise be used to construct both valid and unique layouts.  That _really_ sucks.  😞

**Comment by lulupointu** [comment] 2021-05-12 21:14
Honestly I have never not been able to build a said layout, even with stacks.

However maybe I am missing something, sorry for not being able to help you...

**Comment by lulupointu** [comment] 2021-05-23 10:06
Closing this since it's not an issue with VRouter, feel free to follow at https://github.com/flutter/flutter/issues/14803#issue-298978507 for eventual updates from the Flutter team.

**Closed by lulupointu** 2021-05-23 10:06 UTC
Labels: has reproducible steps
