### ISSUE TITLE
how to remove "#" in url when I upgrade after version 1.1.2+5

### ISSUE THREAD

**Issue by mitesh77** [lulupointu/vrouter#112] opened 2021-07-08 11:25 UTC
version vrouter: 1.1.2+5 is working well but after we set 1.1.3 and above then I got in my URL "#" (for example my URL is "http://localhost:51871/#/dashboard/user" ), this thing. 
I also did `setUrlStrategy(PathUrlStrategy());` but not work after 1.1.3 and above.
what is the solution for that?

**Comment by lulupointu** [comment] 2021-07-08 11:29
Duplicate of https://github.com/lulupointu/vrouter/issues/18

**Comment by lulupointu** [comment] 2021-07-08 11:49
Feel free to reopen if you feel this is not a duplicate.

**Closed by lulupointu** 2021-07-08 11:49 UTC
