### ISSUE TITLE
[Feature request] allow to path params other than String

### ISSUE THREAD

**Issue by TatsuUkraine** [lulupointu/vrouter#188] opened 2022-04-14 08:25 UTC
Vue Router allows using params to path data that is not necessarily defined in the URL itself. Other packages allow path extra params during the navigation.

The use case is simple: dev may have already loaded data that he would like to pass forward during the navigation to reduce the number of API requests or reduce the time that is needed for page render

**Comment by lulupointu** [comment] 2023-04-28 18:34
Duplicate of https://github.com/lulupointu/vrouter/issues/177

**Closed by lulupointu** 2023-04-28 18:34 UTC
