### ISSUE TITLE
Error on Deeplink on iOS

### ISSUE THREAD

**Issue by Lyokone** [lulupointu/vrouter#110] opened 2021-07-04 16:48 UTC
Hi, 
First of all thanks for your package, it makes using Navigator 2.0 so easy :D 
I've been trying to achieve deeplinking with it on iOS without success.

I have a route with the following path : `/event/:id`
AfterI have used this documentation to add deeplinking on my iOS app : https://flutter.dev/docs/development/ui/navigation/deep-linking.

When i run `xcrun simctl openurl booted customscheme://flutterbooksample.com/event/EGm8O6y70nfbR8xoP5YP` in my terminal, I have the following log:
```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Exception: replaceHistoryState should only be used on the web
#0      BrowserHelpers.replaceHistoryState
package:vrouter/…/browser_helpers/browser_helpers_none.dart:15
#1      VRouterDelegate._updateUrl
package:vrouter/…/core/vrouter_delegate.dart:677
<asynchronous suspension>
#2      VRouterDelegate.setNewRoutePath
package:vrouter/…/core/vrouter_delegate.dart:1408
<asynchronous suspension>
```

How could I fix this ?

Thanks a lot

**Comment by lulupointu** [comment] 2021-07-04 17:06
Hey, this is because deep linking is not supported other than web in `v1.1`.

This was actually due to a small mistake and easily corrected for `v1.2` which will be coming out in a few day.
I'll ping you here once it's up!

**Comment by Lyokone** [comment] 2021-07-04 17:06
I've track it down to the `VRouterDelegate` file. In the `setNewRoutePath` method, if I change the 
```
      await _updateUrl(
        routeInformation.location!,
        newHistoryState: newHistoryState,
        fromBrowser: true,
        newSerialCount: newSerialCount ?? _serialCount + 1,
      );
```

into 

```
      await _updateUrl(
        routeInformation.location!,
        newHistoryState: newHistoryState,
        fromBrowser: Platform.isWeb,
        newSerialCount: newSerialCount ?? _serialCount + 1,
      );
```

**Comment by lulupointu** [comment] 2021-07-04 17:29
Mmm, if you only use this on mobile it will be fine. However if your app is also targeting web this will likely cause issue

**Comment by lulupointu** [comment] 2021-07-05 16:41
Hey,

`v1.2` is out. I did not test deep linking specifically but I did solve the issue you were facing. That would be great if you could update and tell me if it's working!

**Comment by Lyokone** [comment] 2021-07-05 16:59
Hi, thanks for the info.
I've tested on both Android and iOS.
On iOS everything is working as expected.
On Android, there is problem on cold start. If the app isn't launched before opening the deeplink, I'm redirect on the home page. If the app is launched in background it works properly.

**Comment by lulupointu** [comment] 2021-07-05 18:02
Wow nice catch, I read too fast and did not see the difference!


I'll do some test and come back when it's fixed.

Thanks for the fast response!

**Comment by lulupointu** [comment] 2021-07-05 20:09
Actually I think everything is working.

I agree that when your app is attached and you close it with the home button, it does not work. 
However this issue is not linked to `VRouter`, indeed I could yield it with [the application of the flutter team which uses Vanilla Navigator 2](https://github.com/flutter/samples/blob/master/navigation_and_routing/lib/router/router.dart).

Nonetheless the great news is that if you detach your app, everything is working as expected. Which means that in production the issue won't appear.

Please tell me if you arrive at the same results

**Comment by Lyokone** [comment] 2021-07-05 22:00
Thanks for the investigation.
I'm not sure what you mean by "detach the app". But when I install the apk from `flutter build apk`, I still have no deep linking into a nested route, while it's working fine on iOS.
If you believe it's a issue with the Navigator 2.0, maybe I can raise an issue directly there ?

**Comment by lulupointu** [comment] 2021-07-05 22:09
This is weird, I thought this would work with `flutter build apk`.

Could you do the same process with this:
  - https://flutter.dev/docs/development/ui/navigation/deep-linking#behavior
  - And using the official test app: https://github.com/flutter/samples/blob/master/navigation_and_routing/lib/router/router.dart

This does not use VRouter so it should tell us if this is a VRouter issue or not.

If you manage to yield the issue with Flutter demo app, please raise an issue on the github repo (check if their isn't one already and detail your problem). Then link it here I will upvote it.

If the problem does not appear there, then this is an issue with VRouter and I would need a small reproducible example with a step by step of what you are doing (similar to what you would write to the Flutter team if the issue was on their end).
For the small reproducible example using vrouter I think you could use the [Basic example from vrouter.dev](https://vrouter.dev/guide/Examples/Basic%20example) if you don't want to waste your time.

**Comment by Lyokone** [comment] 2021-07-06 06:37
Hi, I've just tried the official test app and the deeplinking is working properly there (even in debug mode, after having close the application).
I'll create a small reproductible example and ping you here.
Thanks for your help :)

**Comment by Lyokone** [comment] 2021-07-06 06:46
I've created this small repo with the adb command in the README:
https://github.com/Lyokone/vrouter_example

**Comment by lulupointu** [comment] 2021-07-06 08:19
Thanks again for your patience, I'm sorry that's it's not working.

Could you specify exactly the step you take to yield the error?

For example:
  - use `flutter run` on Android emulator
  - wait for the app to load
  - close the app with the home button
  - use `adb shell am start -a android.intent.action.VIEW \
    -c android.intent.category.BROWSABLE \
    -d "http://vrouter.com/settings"
`
 
Expected: the app opens on the `/settings` tab
Got: the app opens on the `/home` tab

**Comment by Lyokone** [comment] 2021-07-06 08:23
For sure.
- use `flutter run` on real device (OnePlus 7 Pro)
- wait the app to run
- close the app with the home button
- go into recent apps and swipe the app away to properly close the app
- use adb shell am start -a android.intent.action.VIEW \ -c android.intent.category.BROWSABLE \ -d "http://vrouter.com/settings"

Expected: the app opens the `/settings` page
Got: opens the home page

We can note that not 'swiping the app away' make the expected result.

**Comment by lulupointu** [comment] 2021-07-06 09:24
Ok I can reproduce the issue.

I'll get back to you when it's fixed

**Comment by lulupointu** [comment] 2021-07-06 09:59
I think this is solved. I pushed the update on github only so that you can test and tell my if this is working for you as well.

Could you use the github version using the following in `pubspec.yaml`:
```yaml
  vrouter:
    git:
      url: git@github.com:lulupointu/vrouter.git
      ref: main
```

And tell me whether it's working for you or not

**Comment by Lyokone** [comment] 2021-07-06 11:55
Perfect it's working fine! thanks a lot 😄

**Comment by lulupointu** [comment] 2021-07-06 11:56
Ok I'll push the fix then, thanks for your time :wink:

**Closed by lulupointu** 2021-07-06 11:56 UTC

**Comment by lulupointu** [comment] 2021-07-06 12:00
Pushed in `v1.2.0+3`
